### ISSUE TITLE
Allow rule costumization

### ISSUE THREAD

**Issue by fega** [smileytechguy/MaterializeBot#10]
Please don't Harcode the rules to allow easy extensibility :smile:

**Comment by ncovercash** [comment]
By rules you mean the rules for html and js validation?  Right now I'm using tidy for HTML, and am working on jshint + custom rules for javascript

**Comment by fega** [comment]
The rules in general, in that way it could be used out of the materialize project,

**Comment by ncovercash** [comment]
Good idea.  I'll also function out the custom materialize rules (like declaration etc)

**Comment by fega** [comment]
It could be organized as a hooks I don't have so much experience with php but in js it could look similar to 

```
//requires... 
module.exports={
onCreate: [function1, function2], 
onUpdate:... 
"onLabel-bug":... 
}
```

**Comment by ncovercash** [comment]
I got what you mean, its a good idea. I'll add it in later, once I get to that point

**Comment by ncovercash** [comment]
im gonna go ahead and close this.  take a look at what I've done, i added a list of what to change for another project, and generalized methods.
