### ISSUE TITLE
Console JS errors

### ISSUE THREAD

**Issue by ncovercash** [smileytechguy/MaterializeBot#11]

**Comment by ncovercash** [comment]
I have no idea how to implement this well with PHP.  If anyone knows how, even in other languages, let me know

**Comment by fega** [comment]
I guess that you could use something like selenium webdriver or chrome headless and check if it throws an error in any moment

**Comment by NonameSLdev** [comment]
Perhaps we could take all the JS code from the remote website and run it on a local file with error catching:
```
window.onerror = function() {
    alert("Error caught");
};
```
[This doesn't support Opera 1.50- though.](http://stackoverflow.com/questions/645840/mimic-window-onerror-in-opera-using-javascript)

**Comment by ncovercash** [comment]
True. I will look into this,I have been meaning to look at chrome headless
Also, there may be a solution with jsc (WebKit cli command)

**Comment by ncovercash** [comment]
done
images are rendered too
