### ISSUE TITLE
Make run open new thread instead of infinite while loop

### ISSUE THREAD

**Issue by NonameSLdev** [smileytechguy/MaterializeBot#14]
The `run` function just opens a loop and sleeps. That's pretty bad - there's no way to stop the running without stopping the program.
We should replace it with an async thread that re-runs every X seconds (until another function tells it to stop).

**Comment by ncovercash** [comment]
I get where youre coming from, infinite loops are bad.
Currently compiling php with thread safety and such, hope to get it working

**Comment by ncovercash** [comment]
Yeah, im giving up on threading right now

The thread extension is not working well on php 7.1, and i dont feel like forcing composer to work right with it.

Maybe in the future

**Comment by ncovercash** [comment]
see start.sh, it threads with POSIX
