### ISSUE TITLE
Make bot auto-assign "has-pr" label

### ISSUE THREAD

**Issue by NonameSLdev** [smileytechguy/MaterializeBot#15]
## Configurable variables:
 - String `HAS_PR_LABEL_NAME` (default: "has-pr")
 - String `PR_FIXES_ISSUE_REGEX` (default: ?)
## Behaviour:
 - ~~Runs on a _different thread_ than the regular syntax checker (so it could have different configurable time).~~
 - Option A: Loop through issues
   - Loops through recently updated open issues, skipping issues that have that have the `HAS_PR_LABEL_NAME` label.
   - Checks for PRs referencing it in the issue body (_If possible_).
   - If a PR does reference it, add the `HAS_PR_LABEL_NAME` label and leave a short comment saying that it's been auto added, and if this is a mistake to contact collaborators/maintainers or to edit the issue body to say that the label should be removed.
 - Option B: Loop through PRs
   - Loops through _recently updated_ PRs, checks for it referencing issues, checks for the title being/body matching `PR_FIXES_ISSUE_REGEX`.
   - If there's an issue referenced and it doesn't have the `HAS_PR_LABEL_NAME` label, it adds it.
   - It doesn't go through checked errors that weren't recently updated

_Option A is only better if it's possible to check for referencing PRs in the issue body. If we can't do that then option B is better._

**Comment by ncovercash** [comment]
I think the way to do this is to download list of PRs (due to the same numbering scheme), then download the issues and iterate there.  I'm going to look into pagination for that.

**Comment by NonameSLdev** [comment]
@smileytechguy We have to download PRs/issues? We can't just do it remotely?

**Comment by ncovercash** [comment]
not download, wrong term
we have to just store a list of what numbers go to what as a variable in the bot
its strange the distinction between issues and prs

**Comment by ncovercash** [comment]
done
