### ISSUE TITLE
similar issues

### ISSUE THREAD

**Issue by ncovercash** [smileytechguy/MaterializeBot#16]

**Comment by NonameSLdev** [comment]
Similar issues to...

**Comment by ncovercash** [comment]
oh it was a note for me
Im gonna make a "Similar issues" section
that gives a list of issues similar to the one posted

**Comment by ncovercash** [comment]
![image](https://cloud.githubusercontent.com/assets/8005215/25073381/6b087986-22b3-11e7-9e08-8711ac6e4cb1.png)
done!
