### ISSUE TITLE
Detect Materialize code mistakes

### ISSUE THREAD

**Issue by NonameSLdev** [smileytechguy/MaterializeBot#3]
Add support for detecting if...
- Materialize isn’t included / the latest version isn’t included in the code (Live examples only)
- Materialize component verifying fails. Includes:
  - Element that needs to be initialized isn’t initialized. (Live examples only)
  - Inproper syntax of element (HTML syntax of materialize element)

**Comment by ncovercash** [comment]
Done (first part at least)

**Comment by ncovercash** [comment]
Fixed overall

**Comment by fega** [comment]
Check if jquery is included before materialize

**Comment by ncovercash** [comment]
Okay I will try

**Comment by ncovercash** [comment]
I cannot check if jquery is initialized very well.  However, I am currently attempting to use selenium to render the page myself

**Comment by ncovercash** [comment]
So that will show if the page works when correctly including jquery

**Comment by NonameSLdev** [comment]
We can, if we detect index of a jquery including regex and compare it to a materialize including regex while parsing the page

> I cannot check if jquery is initialized very well. However, I am currently attempting to use selenium to render the page myself

**Comment by ncovercash** [comment]
There are many ways to include it however, as a library, or from the dropdown.  I'll mess with it some

**Comment by ncovercash** [comment]
I cant very well detect if it is missing, however i added a note with the screenshot saying that if it is wildly different from yours, then it may be due to dependencies

**Comment by fega** [comment]
If you can detect console errors you could read the common "$ is not defined"

**Comment by ncovercash** [comment]
@fega to detect console errors, i take the js/html out of the pen/fiddle/markdown and dump it into a local file.  From there, I check for issues

**Comment by ncovercash** [comment]
the local wile contains jquery and materialize
