### ISSUE TITLE
Make a function to scan new issues and validate them

### ISSUE THREAD

**Issue by NonameSLdev** [smileytechguy/MaterializeBot#6]
Title.

**Comment by ncovercash** [comment]
automatic, refreshes every 2s, but should probably be expanded to 10+s

**Comment by NonameSLdev** [comment]
@smileytechguy Should also be configurable. We could even make it every minute, it's not like issues are updated every 10 seconds.

**Comment by ncovercash** [comment]
I'll add a constant for it

**Comment by fega** [comment]
it should also validate if the body of the issue is not empty

**Comment by ncovercash** [comment]
It does and checks if the template is unfollows

**Comment by ncovercash** [comment]
Unfilled*

**Comment by ncovercash** [comment]
Check out Bot::getEmptyBody and Bot::getUnfilledTemplate
