### ISSUE TITLE
Add a functionality to detect inactive issues and handle them

### ISSUE THREAD

**Issue by NonameSLdev** [smileytechguy/MaterializeBot#8]
There needs to be a configurable amount of time without any activity for an issue to be considered inactive.
**If there's an open PR for the issue, it should not be detected as inactive no matter what.**
If that time has passed and the bot hasn't commented on it yet, it needs to comment with a configurable syntax a message saying that the issue will be closed in (configurable amount of time to save issue from being closed) from now if there's no new activity.

**Comment by ncovercash** [comment]
Does materialize use the has-pr label consistently?

**Comment by fega** [comment]
Well, in this moment no, but personally,   I'm trying to label everything as posible, but it drains my energy, so it will take a while... 

But that's the goal :smile:

**Comment by NonameSLdev** [comment]
@fega @smileytechguy IDEA; Bot functionality to auto-label issues referenced in PRs with `has-pr`. Discuss

**Comment by fega** [comment]
But the bot could check the PRs looking for the keyword solves, fix, fixes and put the respective `has-pr` label

Edit: oh! I said the same of @NonameSLdev

**Comment by ncovercash** [comment]
I can look into that. It'd have to have a list of all PRs and scan for those numbers. I'll look into that

**Comment by ncovercash** [comment]
https://github.com/smileytechguy/issueTesting/issues/121

How does this look?

Don't worry, its normally 21 days of inactive and 7 days to respond, i altered to test

Also, to stop it:
https://github.com/smileytechguy/issueTesting/issues/122
