### ISSUE TITLE
Code change detection - Automatic or manual?

### ISSUE THREAD

**Issue by NonameSLdev** [smileytechguy/MaterializeBot#9]
We have two options:
The first option is that the bot saves the code(s) for each issue and detects changes every once in a while (which would take up space and would be inefficient).
The second option is that change detections wouldn't be automatic and people will be able to comment "@MaterializeBot review the code" and it will.
I think that the second option is better.

**Comment by ncovercash** [comment]
Im gonna go with manual

**Comment by ncovercash** [comment]
auso would be too much work

**Comment by fega** [comment]
Why not check the latest comment date instead, and compare when the last check was done?

**Comment by ncovercash** [comment]
@fega It'd still be checking each issue, and that would heavily overload github API limits

**Comment by fega** [comment]
We can avoid this problem with web scrapping, sorting the issues result by `recently updated `

**Comment by ncovercash** [comment]
Thats a good idea, I'll look into that once I get to that point.

**Comment by NonameSLdev** [comment]
@fega @smileytechguy In that case we could do that and check the errors in MaterializeBot's last comment  instead of saving the whole code and comparing them to the new issues. What do you think?

**Comment by ncovercash** [comment]
It's pretty easy just to check errors again. The way I'm doing it currently is using a external tool, and formatting output. What's probably best is to rescan/make a new comment, and edit the old one to say something like "This comment is outdated. Please see the updated version below" or something

But that's still a bit out

**Comment by ncovercash** [comment]
working

**Comment by ncovercash** [comment]
see https://github.com/smileytechguy/issueTesting/issues/77
